- name: Get Facts
  debug:
      msg: 
        -  "ansible_lsb.major_release: {{ansible_lsb.major_release}}"

- name: install zsh
  apt:
      name: zsh
      state: present

- name: install tmux
  apt:
      name: tmux
      state: present

- name: install curl
  apt:
      name: curl
      state: present

- name: install python
  apt:
      name: python
      state: present

- name: Install python-pip (Bionic Beaver)
  apt:
      name: python-pip
      state: present
  when: "ansible_lsb.major_release == '18'"

- name: Install python-pip (Focal Fossa)
  shell: "mkdir -p /opt/install/pip2 && curl https://bootstrap.pypa.io/get-pip.py --output /opt/install/pip2/get-pip.py && python2 /opt/install/pip2/get-pip.py"
  when: "ansible_lsb.major_release == '20'"

- name: install python3
  apt:
      name: python3
      state: present

- name: install python3-pip
  apt:
      name: python3-pip
      state: present

- name: install socat
  apt:
      name: socat
      state: present

- name: install vim
  apt:
      name: vim
      state: present

- name: install rsync
  apt:
      name: rsync
      state: present

- name: install git
  apt:
      name: git
      state: present

- name: install unattended-upgrades
  apt:
      name: unattended-upgrades
      state: present

- name: htop
  apt:
      name: htop
      state: present

- name: wireguard
  apt:
      name: wireguard
      state: present
