- name: brute clone
  git: 
      repo: "{{ item.url }}"
      dest: "/opt/brute/{{ item.name }}"
      #clone: no
      update: yes
      version: "{{ item.branch }}"
  with_items:
      - "{{ git_repos }}"
  ignore_errors: yes

- name: post clone configuration
  shell: "{{ item.shell }}"
  with_items:
      - "{{ git_repos }}"
  ignore_errors: yes
